`default_nettype none

// ============================================================
// TinyTapeout PolyTrig Project
// ------------------------------------------------------------
// This module implements:
//
//   mode = 0  --> sine
//   mode = 1  --> cosine
//
// using:
//
//   - 8-bit phase representation
//   - quarter-wave symmetry reconstruction
//   - compact 17-point quarter-wave LUT
//   - 2-bit linear interpolation
//   - unsigned 8-bit output representation
//
// ------------------------------------------------------------
// Phase representation:
//
//   phase = 0     ->   0°
//   phase = 64    ->  90°
//   phase = 128   -> 180°
//   phase = 192   -> 270°
//
// Full scale:
//
//   256 steps = 360°
//
// ------------------------------------------------------------
// Output representation:
//
//   0     = minimum value (-1)
//   128   = zero crossing
//   255   = maximum value (+1)
//
// ------------------------------------------------------------
// Cosine implementation:
//
//   cos(x) = sin(x + 90°)
//
// Since:
//
//   90° = 64 phase counts
//
// cosine is generated by adding 64 to the input phase.
//
// ------------------------------------------------------------
// Interpolation idea:
//
// Instead of storing all 64 quarter-wave samples, we store
// only 17 coarse samples.
//
// The 6-bit quarter-wave position is split into:
//
//   quarter_pos[5:2] = segment index
//   quarter_pos[1:0] = fractional position inside segment
//
// Then:
//
//   mag = y0 + ((y1 - y0) * frac) / 4
//
// This gives smoother output with small hardware cost.
//
// ------------------------------------------------------------
// Pipeline:
//
//   Cycle 0:
//      start asserted, phase/mode sampled
//
//   Cycle 1:
//      quadrant decode, LUT lookup, interpolation
//
//   Cycle 2:
//      result registered, valid asserted
//
// ============================================================

module sine_cos_lut (

    // System clock
    input  wire       clk,

    // Active-low reset
    input  wire       rst_n,

    // Start pulse
    input  wire       start,

    // Function select:
    //   0 -> sine
    //   1 -> cosine
    input  wire       mode,

    // 8-bit phase input
    input  wire [7:0] phase,

    // 8-bit unsigned sine/cosine output
    output reg  [7:0] result,

    // Output valid pulse
    output reg        valid
);

    // ========================================================
    // Internal Registers / Signals
    // ========================================================

    // Internal phase used for sine calculation.
    //
    // For sine:
    //   phase_used = phase
    //
    // For cosine:
    //   phase_used = phase + 64
    //
    reg [7:0] phase_used;

    // First pipeline valid stage.
    //
    // valid_s1 marks that sampled phase_used is active.
    // valid marks that output result is active.
    //
    reg valid_s1;

    // Quadrant number:
    //
    //   00 -> Q0:   0° to  90°
    //   01 -> Q1:  90° to 180°
    //   10 -> Q2: 180° to 270°
    //   11 -> Q3: 270° to 360°
    //
    reg [1:0] quadrant;

    // Position inside current quadrant
    reg [5:0] index;

    // Mirrored quarter-wave position after symmetry mapping
    reg [5:0] quarter_pos;

    // Segment index for compact LUT.
    //
    // 16 coarse segments inside quarter-wave.
    //
    reg [3:0] seg_index;

    // Fractional position inside segment.
    //
    // 00 -> y0
    // 01 -> y0 + 1/4 delta
    // 10 -> y0 + 2/4 delta
    // 11 -> y0 + 3/4 delta
    //
    reg [1:0] frac;

    // Coarse LUT endpoint values
    reg [6:0] y0;
    reg [6:0] y1;

    // Difference between LUT endpoints
    reg [6:0] delta;

    // Small interpolation product:
    //
    //   delta * frac
    //
    reg [6:0] interp_step;

    // Final unsigned magnitude before sign reconstruction
    //
    // Range:
    //   0 -> 127
    //
    reg [6:0] mag;

    // Sign flag:
    //
    //   0 -> positive half-wave
    //   1 -> negative half-wave
    //
    reg negative;

    // ========================================================
    // Stage 1
    // --------------------------------------------------------
    // Sample input phase and mode.
    //
    // Convert cosine into sine phase by adding 90°.
    //
    // In 8-bit phase format:
    //
    //   90° = 64
    //
    // ========================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            phase_used <= 8'd0;
            valid_s1   <= 1'b0;
            valid      <= 1'b0;

        end else begin

            valid_s1 <= start;
            valid    <= valid_s1;

            if (start) begin

                // --------------------------------------------
                // Cosine:
                //
                //   cos(x) = sin(x + 90°)
                //
                // --------------------------------------------

                if (mode)
                    phase_used <= phase + 8'd64;

                // Pure sine
                else
                    phase_used <= phase;

            end
        end
    end

    // ========================================================
    // Quadrant Decode + Symmetry Reconstruction
    // --------------------------------------------------------
    //
    // Only the first quarter-wave is approximated:
    //
    //   0° -> 90°
    //
    // The other quadrants are reconstructed using sine symmetry.
    //
    // This avoids storing a full 256-entry sine table.
    //
    // ========================================================

    always @(*) begin

        // Upper 2 bits define quadrant
        quadrant = phase_used[7:6];

        // Lower 6 bits define position inside quadrant
        index = phase_used[5:0];

        case (quadrant)

            // =================================================
            // Q0 : 0° -> 90°
            //
            // Positive rising sine
            //
            // Use quarter-wave position directly.
            // =================================================

            2'b00: begin

                quarter_pos = index;
                negative    = 1'b0;

            end

            // =================================================
            // Q1 : 90° -> 180°
            //
            // Positive falling sine
            //
            // Mirror around 90°.
            // =================================================

            2'b01: begin

                quarter_pos = 6'd63 - index;
                negative    = 1'b0;

            end

            // =================================================
            // Q2 : 180° -> 270°
            //
            // Negative falling sine
            //
            // Same magnitude shape as Q0, but negative.
            // =================================================

            2'b10: begin

                quarter_pos = index;
                negative    = 1'b1;

            end

            // =================================================
            // Q3 : 270° -> 360°
            //
            // Negative rising sine
            //
            // Same magnitude shape as Q1, but negative.
            // =================================================

            default: begin

                quarter_pos = 6'd63 - index;
                negative    = 1'b1;

            end
        endcase
    end

    // ========================================================
    // Quarter-Wave Position Split
    // --------------------------------------------------------
    //
    // quarter_pos is 6 bits:
    //
    //   0 -> 63
    //
    // Instead of using all 64 values as a LUT address, split it:
    //
    //   upper 4 bits -> coarse segment address
    //   lower 2 bits -> interpolation fraction
    //
    // ========================================================

    always @(*) begin

        seg_index = quarter_pos[5:2];
        frac      = quarter_pos[1:0];

    end

    // ========================================================
    // 17-Point Quarter-Wave LUT
    // --------------------------------------------------------
    //
    // The LUT stores coarse samples for:
    //
    //   sin(0° -> 90°)
    //
    // scaled to magnitude:
    //
    //   0 -> 127
    //
    // Each segment provides:
    //
    //   y0 = segment start value
    //   y1 = segment end value
    //
    // Interpolation then estimates values between y0 and y1.
    //
    // ========================================================

    always @(*) begin

        case (seg_index)

            4'd0: begin
                y0 = 7'd0;
                y1 = 7'd12;
            end

            4'd1: begin
                y0 = 7'd12;
                y1 = 7'd25;
            end

            4'd2: begin
                y0 = 7'd25;
                y1 = 7'd37;
            end

            4'd3: begin
                y0 = 7'd37;
                y1 = 7'd49;
            end

            4'd4: begin
                y0 = 7'd49;
                y1 = 7'd60;
            end

            4'd5: begin
                y0 = 7'd60;
                y1 = 7'd70;
            end

            4'd6: begin
                y0 = 7'd70;
                y1 = 7'd80;
            end

            4'd7: begin
                y0 = 7'd80;
                y1 = 7'd90;
            end

            4'd8: begin
                y0 = 7'd90;
                y1 = 7'd98;
            end

            4'd9: begin
                y0 = 7'd98;
                y1 = 7'd106;
            end

            4'd10: begin
                y0 = 7'd106;
                y1 = 7'd113;
            end

            4'd11: begin
                y0 = 7'd113;
                y1 = 7'd117;
            end

            4'd12: begin
                y0 = 7'd117;
                y1 = 7'd122;
            end

            4'd13: begin
                y0 = 7'd122;
                y1 = 7'd125;
            end

            4'd14: begin
                y0 = 7'd125;
                y1 = 7'd127;
            end

            // Final segment reaches the peak and stays saturated.
            default: begin
                y0 = 7'd127;
                y1 = 7'd127;
            end

        endcase
    end

    // ========================================================
    // Linear Interpolation
    // --------------------------------------------------------
    //
    // Compute:
    //
    //   mag = y0 + ((y1 - y0) * frac) / 4
    //
    // Because frac is 2 bits, division by 4 is just:
    //
    //   [8:2]
    //
    // Special case:
    //
    //   quarter_pos = 63
    //
    // must produce exactly:
    //
    //   mag = 127
    //
    // so that 90° reaches output 255.
    //
    // ========================================================

    always @(*) begin

    delta = y1 - y0;

    case (frac)
        2'd0: interp_step = 7'd0;
        2'd1: interp_step = delta >> 2;
        2'd2: interp_step = delta >> 1;
        default: interp_step = (delta >> 1) + (delta >> 2);
    endcase

    if (quarter_pos == 6'd63)
        mag = 7'd127;
    else
        mag = y0 + interp_step;

    end

    // ========================================================
    // Stage 2
    // --------------------------------------------------------
    // Register final output.
    //
    // Convert signed sine magnitude into unsigned 8-bit output.
    //
    // Positive half-wave:
    //
    //   result = 128 + mag
    //
    // Negative half-wave:
    //
    //   result = 128 - mag
    //
    // ========================================================

    always @(posedge clk or negedge rst_n) begin

        if (!rst_n) begin

            // Midscale output
            result <= 8'd128;

        end else begin

            if (valid_s1) begin

                // Negative half-wave
                if (negative)
                    result <= 8'd128 - {1'b0, mag};

                // Positive half-wave
                else
                    result <= 8'd128 + {1'b0, mag};

            end
        end
    end

endmodule

`default_nettype wire